olincollege/p2p-networking

- src/CMakeLists.txt
- src/hash.c
- src/hash.h
- src/hello.c
- src/hello.h
- src/network.c
- src/network.h
- test/CMakeLists.txt
- test/test_hello.c
moved declarations into header files
> add headers for files

- src/CMakeLists.txt
- src/message.h
- test/CMakeLists.txt
- test/test_message.c
In our last meeting we discussed how we should encode messages between clients. The adds a header file `message.h` formalizing this into C structs.
> Message types

- src/network.c
- src/network.h
Implemented the full_message_available() function which uses the MSG_PEEK flag to determine if a full message has been received without clearing the message.
> Implemented message peeking for determining if a message is available.

- src/hash.c
- src/hash.h
- src/hash_table.c
- src/hash_table.h
- src/loop.c
- src/message.h
- src/network.c
- src/vector.h
- test/test_hash_table.c
- test/test_message.c
- test/test_vector.c
> Ran Clang-Format on all C files

- src/loop.c
- src/network.c
- src/network.h
Implemented receiving and reading ask, give, and peer messages.
> Implemented Received Message Parsing (#27)

- src/network.c
removed EPOLLET flag which specifies edge triggering and we don't want that
> switch to level triggering

- .github/workflows/tests.yaml
- src/network.c
- src/network.h
- test/CMakeLists.txt
- test/test_network.c
https://github.com/olincollege/p2p-networking/issues/25
> add code for increasing socket buffer

- src/hash_table.c
closes #39 
this wasted an embarrassingly long amount of time.  I did learn how to attach a debugger to criterion though which is cool: 
https://criterion.readthedocs.io/en/master/debug.html
> hash table realloc bug

- src/state.c
- src/state.h
- test/test_state.c
Starts to implement ability to broadcast wanted pieces. Recycles from PR: https://github.com/olincollege/p2p-networking/pull/42 for the most part.
PR put in before implementation is finished so review and discussion can take place
Addresses #33
> Implement function to broadcast wanted pieces

- src/loop.c
Includes updates to read_message.
Adds connect_to_list and connect_to_peer.
Fixes issue 48.
> Update state based on received messages.

- src/loop.c
- src/state.c
- src/state.h
> more lint errors

- src/loop.c
> Bootstrapping/Broadcasting Partially Works (does not crash atleast) 

- src/hash.h
- src/hash_table.h
- src/network.h
- src/state.h
> Documentation comments

- src/loop.c
- src/loop.h
No major changes, just rearranging code.
> Replaced epoll binding code with call to bind_epoll() function

- src/state.c
- src/state.h
> Remove hash from wanted pieces on receiving a piece

- src/loop.c
recv should take message_len not sizeof(message).
> Fixed receive not reading the correct amount of bytes

- src/state.c
> Fix send if have bug

- src/network.h
> inc MAX_SIZE_MESSAGE_INT

- readme.md
> Add build and execution instructions

- src/hash.h
- src/hash_table.c
- src/hash_table.h
- src/loop.c
- src/loop.h
- src/network.c
- src/network.h
- src/state.c
- src/state.h
PR compiles without any warnings! (On my machine™)
- Adds documentation comments for `loop.h` and `hash.h`.
- Declares several local functions as static
- Fixes contradictory argument names in `.h/.c` and a misspelled variable name
- Functions with no argument have `void` as their argument
Resolves #85 
Resolves #84
> Compilation and documentation improvements
